library constants;

const FINISHED_ON_BOARDING = 'finishedOnBoarding';
const COLOR_ACCENT = 0xFF80DEEA; //LIGHT CYAN
const COLOR_PRIMARY_DARK = 0xFF0288D1; //LIGHT BLUE
const COLOR_PRIMARY = 0xFF00BCD4; //CYAN
const COLOR_WORDING = 0xFF01579B; //DARK BLUE
const USERS = 'users';
